config/routes.rb
DevPostIt::Application.routes.draw do

  resources :post_its do
    get 'last_updated', :on => :collection
  end

  root :to => 'post_its#index'

end

app/models/post_it.rb
class PostIt < ActiveRecord::Base
  after_validation :initialize_token, :on => :create
 
  attr_protected :token
  
  validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i, :presence => true
  validates :title, :content, :username, :presence => true
  
  self.per_page = Settings.nb_post_its_per_page
  
  def self.last_updated
    PostIt.order('updated_at DESC, id DESC').limit(1).first
  end
  
  def allow_modification? token
    not token.blank? and self.token == token
  end
  
  # used for formatting code with plugin syntax_highlighter
  def brush
     if self.language.blank?
       'plain'
     else
       self.language.downcase
     end
  end
  
  protected

  def initialize_token
    self.token = Digest::MD5.new.hexdigest(Time.now.to_i.to_s + SecureRandom.random_bytes(512) + Settings.salt_token)
  end
  
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/post_its_controller.rb
class PostItsController < ApplicationController
  # GET /post_its
  # GET /post_its.json
  def index
    @post_its = PostIt.order('updated_at DESC, id DESC').page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @post_its, :only => [:id, :username, :title, :updated_at] }
    end
  end
  
  # GET /post_its/last_updated
  def last_updated    
    render :json => PostIt.last_updated, :only => [:updated_at]
  end

  # GET /post_its/1
  # GET /post_its/1.json
  def show
    @post_it = PostIt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post_it }
    end
  end

  # GET /post_its/new
  # GET /post_its/new.json
  def new
    @post_it = PostIt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post_it }
    end
  end

  # GET /post_its/1/edit
  def edit
    @post_it = PostIt.find(params[:id])
    
    unless @post_it.allow_modification? params[:token]
      return redirect_to root_path, :alert => "Vous n'avez pas les droits pour modifier ce post-it"
    end
  end

  # POST /post_its
  # POST /post_its.json
  def create
    @post_it = PostIt.new(params[:post_it])

    respond_to do |format|
      if @post_it.save
        PersonMailer.new_post_it(@post_it).deliver
        format.html { redirect_to @post_it, :notice => 'Post it was successfully created.' }
        format.json { render :json => @post_it, :status => :created, :location => @post_it }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post_it.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /post_its/1
  # PUT /post_its/1.json
  def update
    @post_it = PostIt.find(params[:id])
    
    unless @post_it.allow_modification? params[:token]
      return redirect_to root_path, :alert => "Vous n'avez pas les droits pour modifier ce post-it"
    end
    
    respond_to do |format|
      if @post_it.update_attributes(params[:post_it])
        format.html { redirect_to @post_it, :notice => 'Post it was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post_it.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /post_its/1
  # DELETE /post_its/1.json
  def destroy
    @post_it = PostIt.find(params[:id])
    
    unless @post_it.allow_modification? params[:token]
      return redirect_to root_path, :alert => "Vous n'avez pas les droits pour supprimer ce post-it"
    end
    
    @post_it.destroy

    respond_to do |format|
      format.html { redirect_to post_its_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_its_helper.rb
module PostItsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title DevPostIt
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
  
  %body
    -unless notice.blank?
      .flash_messages
        %p.notice= notice
    -unless alert.blank?
      .flash_messages
        %p.alert= alert

    = yield

app/views/post_its/_form.html.haml
= semantic_form_for @post_it do |f|
  = f.inputs do
    = f.input :title
    = f.input :language, :collection => Settings.languages
    = f.input :content
    = f.input :username
    = f.input :email, :required => true
  
  = f.buttons do
    = f.commit_button

%h1 Preview
%pre#preview{:class => 'brush: plain;'}

app/views/post_its/edit.html.haml
%h1 Editing post_it

= render 'form'

= link_to 'Show', @post_it
\|
= link_to 'Back', post_its_path

app/views/post_its/index.html.haml
%h1 Listing post_its

#listing_post_it
  #notice_update Nouveau(x) post-it(s) chargé(s)

  #dummy_post_it.post_it
    .header
      %div
        Par
        %span.username
        Le
        %span.updated_at
      %a.title
  .spinner
  #content

#previous_page Post-its précédents
#current_page
#next_page Post-its suivants

%br

= link_to 'New Post it', new_post_it_path

app/views/post_its/new.html.haml
%h1 New post_it

= render 'form'

= link_to 'Back', post_its_path

app/views/post_its/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post_it.title
%p
  %b Username:
  = @post_it.username

%h1 Code
%pre#content{:class => "brush: #{@post_it.brush};"}= @post_it.content

%h1 Code (raw version)
%pre= @post_it.content

= link_to 'Edit', edit_post_it_path(@post_it)
\|
= link_to 'Back', post_its_path